# Generated by Django 6.0.2 on 2026-03-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leaverequest_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
